service: aws-lambda

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1

functions:
  hello:	
    handler: handler.hello
    events:
      - http:
          path: /hello
          method: get
          cors: true
          credentials: true
  
  goodbye:
    handler: handler.goodbye
    events:
      - http:
          path: /goodbye
          method: post
          cors: true
          credentials: true